name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11  
    - name: Puppeteer Container
      uses: ianwalter/puppeteer@v2.0.0
    - name: Build with Gradle
      run: ./gradlew build
    - name: Test with Gradle
      run: ./gradlew test
